---
ansible_connection: ssh
ansible_user: ubuntu
ansible_become: true

kafka_broker_custom_listeners:
  client_listener:
    name: CLIENT
    port: 9093
    ssl_enabled: false
    ssl_mutual_auth_enabled: false
    sasl_protocol: none
